### ISSUE TITLE
multi-gpu running error

### ISSUE THREAD

**Issue by FightingFighting** [OPTML-Group/Unlearn-Saliency#13]
Thank you for this great job.

I just met a problem. when I generate the original model, if I use 1 GPU, it is running well, however, if I run it with two GPUs, I got the following issue. do you know what happened?

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

It seems like that this problem is caused by 
```python
hs = [self.conv_in(x)]
``` 
in models/diffusion.py

**Comment by a-F1** [comment]
Thank you for your interest and support in our work! Unfortunately, our code does not currently support multi-GPUs.

Our stable diffusion model uses the Compvis format. I recommend checking out https://github.com/CompVis/stable-diffusion for more solutions related to multi-GPUs.
