### ISSUE TITLE
No module named 'datasets.load'

### ISSUE THREAD

**Issue by Grassyue** [OPTML-Group/Unlearn-Saliency#17]
Hi, it is a wonderful for and thank you for sharing the code.
When I perform classification task,  there is a mistake happened:

`  File "/data/project/Unlearn-Saliency/Classification/imagenet.py", line 6, in <module>
    from datasets.load import load_dataset
ModuleNotFoundError: No module named 'datasets.load'`

**Comment by a-F1** [comment]
Thank you for your interest in our work. The error message indicates that Python cannot find the module `datasets.load`. You can install it using the following command: `pip install datasets`.

If you have any further questions, please feel free to contact us.

**Comment by a-F1** [comment]
Issue closed. Please feel free to post new responses or initiate another issue if you have further questions. Thanks!
