### ISSUE TITLE
FID Computation

### ISSUE THREAD

**Issue by projectavi** [OPTML-Group/Unlearn-Saliency#18]
I'm trying to reproduce your results for the FID computation.

1. the import may be outdated for the FID as I had to replace FID with FrenechetInceptionDistance to get it to work
2. In the setup_fid_data function you use 
`real_set = Fake_Imagenette(
        "imagenette_without_label_6", class_to_forget, transform=transform
    )`

which doesn't work and doesn't make sense. Could you explain/help with this?

**Comment by a-F1** [comment]
Thank you for your appreciation of our work. Could you please provide more details about your concerns and questions? For example, the command you used and the relevant code details?
