### ISSUE TITLE
The choice of the regularization parameter

### ISSUE THREAD

**Issue by meng-ding** [OPTML-Group/Unlearn-Saliency#21]
Dear Authors,

Thank you for your excellent work on machine unlearning!

I have a question regarding the regularization parameter \alpha in Equation (6) of your paper. Could you please explain how/where you chose the value of \alpha and the range it was selected from? Specifically, does the parameter range from 0 to 1?

Best regards,

**Comment by a-F1** [comment]
Thank you for your appreciation and interest in our work. The value of \alpha in Eq6 is set to 1. 
If you have any further questions, please don't hesitate to contact us.

**Comment by meng-ding** [comment]
> Thank you for your appreciation and interest in our work. The value of \alpha in Eq6 is set to 1. If you have any further questions, please don't hesitate to contact us.

Thank you for your responses! I still have two questions: 1) In Equation (6), it appears that the unlearn model is updated by the summation of two losses (\alpha * retain ACC + unlearn ACC). However, in the code, it seems that the unlearn model is updated sequentially—first on the forget data and then on the retain data (as seen in RL.py, lines 88 and 106). Could you help me to understand this? 2) Can the regularization parameter range from [0,1]?

Best,

**Comment by a-F1** [comment]
Yes, our model updates sequentially, first on the forget data and then on the retain data. The alpha can take any value between 0 and 1, and the smaller the alpha, the stronger the forgetting effect. 
If you have any further questions, please feel free to contact us.

**Comment by meng-ding** [comment]
> Yes, our model updates sequentially, first on the forget data and then on the retain data. The alpha can take any value between 0 and 1, and the smaller the alpha, the stronger the forgetting effect. If you have any further questions, please feel free to contact us.

Thanks for your detailed answer! The issue is addressed now. Appreciate your nice work again!
