### ISSUE TITLE
Unlearning specific concepts in SD

### ISSUE THREAD

**Issue by NGK2110** [OPTML-Group/Unlearn-Saliency#22]
Dear authors,

Thank you for sharing your excellent work! I have a question regarding the unlearning of specific concepts.

I noticed that the code you provided can unlearn a set of predefined classes based on the Imagenette dataset. Is it possible to extend this approach to unlearn concepts based on custom prompts or user-defined datasets? 
Is it done by using this custom dataset for concept unlearning?

Could you provide information on how this might be implemented?

**Comment by a-F1** [comment]
Thank you for your interest in our work. Our algorithm supports unlearning specific concepts in SD. For more details, please refer to our approach in the Application to NSFW Concept Forgetting section of 6.2 experiment results and MU for image generation in Appendix C.1. In the NSFW Removal example, the specific concept we targeted for forgetting was nudity.
