### ISSUE TITLE
Request for Experiment Result Data on NSFW Removal from Salun Paper

### ISSUE THREAD

**Issue by anseryuer** [OPTML-Group/Unlearn-Saliency#26]
Hello, I recently read your paper Salun and found the section on NSFW removal very insightful. However, the chart displaying the experiment results in this section isn't clear enough to extract specific data points. Could you please share the detailed experiment result data for the NSFW removal part? This would greatly help in understanding and replicating your findings more accurately.

By the way, one extra question is that the detection using nudenet here is using the threshold value of 0 right? 

Thank you for your time and assistance.

![image](https://github.com/user-attachments/assets/e0f692c0-86b5-44e8-9754-9d02dcc13cf4)

**Comment by a-F1** [comment]
Thank you for your interest in and recognition of our work! Regarding Figure 5, the corresponding numbers for different parts of SalUn are [0, 9, 9, 2, 3, 4, 2, 4]. We used the default threshold of nudenet for detection. 
If you have any further questions, please don't hesitate to contact us!
