### ISSUE TITLE
Question Regarding DDPM Class-Wise Unlearning Iterations

### ISSUE THREAD

**Issue by soyoung2022** [OPTML-Group/Unlearn-Saliency#27]
I read your paper and am currently trying to reproduce the experimental results. However, I have some questions, so I’m posting this issue.

In the paper regarding the DDPM class-wise unlearning experiments, the appendix mentions that 80,000 iterations are used during retraining. When following the sequence of model training → mask generation → unlearning, how many iterations are used for the initial model training? Additionally, in the configs/cifar10_train.yml file, the n_iters in the training section is set to 800,000. Is this correct?

Thank you for your assistance!

**Comment by soyoung2022** [comment]
So, I understand that the retrain iterations are 80,000, and for the initial model training before unlearning, it is 800,000, is this correct?

**Comment by a-F1** [comment]
Thank you for your attention and interest in our work. To train the origin model and retrain for the unlearning process, we used 800,000 iterations. For SalUn, we used 1,000 iterations. 
Please feel free to contact us if you have any further questions!

**Comment by a-F1** [comment]
The issue has been closed. If you have any further questions, feel free to contact us at any time.
