### ISSUE TITLE
Is it possible to directly use Salun with SD2 or even SD3?

### ISSUE THREAD

**Issue by anseryuer** [OPTML-Group/Unlearn-Saliency#28]
Here to setup SD unlearning, we need to download the SD code base and model and then copy the Salun code.

So I wonder is it possible to incorporate it into newer version of SD 2 or SD 3? Have you tried this before or do you have any resource for this?

Thank you!

**Comment by a-F1** [comment]
Thank you for your interest and support for our work! I believe our method can be easily adapted to any version of SD. You just need to adjust the corresponding config and weight files. You can refer to the following link for guidance: https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/train-scripts/random_label.py#L29.

If you have any further questions, please feel free to reach out to us.

**Comment by ljcc0930** [comment]
Issue closed
