### ISSUE TITLE
Erase nudity in Stable diffusion

### ISSUE THREAD

**Issue by TianyunYoung** [OPTML-Group/Unlearn-Saliency#3]
Hello~

I notice that the training script for erasing nudity is not given in [SD/README.md](https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/README.md). Could you share it?

Besides, to repoduce the results for erasing nudity, I encountered some problems:
1. [generate mask](https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/train-scripts/generate_mask.py) for nudity involves a dataset named "data/nsfw". How to get this dataset? 
2. [Saliency unlearning](https://github.com/OPTML-Group/Unlearn-Saliency/blob/master/SD/train-scripts/random_label.py) needs remain_dl for training. How to get the remain data for erasing nudity?

Thank you very much~😁

**Comment by a-F1** [comment]
Thank you for your queries. We will update our training script. Here are my responses to each of your points:

1. Mask: Throughout the Unlearning process, we utilize ‘a photo of a nude person' to derive the weight saliency mask for NSFW concept. Subsequently, we regard ‘a photo of a nude person' as the concept to be forgotten and make correction using the concept ‘a photo of a person wearing clothes.'
2. Dr and Df: we initially employ SD V1.4 to generate 800 images as Df using the prompt ‘a photo of a nude person' and additional 800 images as Dr using the prompt‘a photo of a person wearing clothes.'

I hope these responses clarify your concerns and aid in your further experiments.

**Comment by TianyunYoung** [comment]
I understand. Thank you very much for your clear response.

**Comment by YtengTan** [comment]
Hello authors,

Thank you for open source of your amazing work!

I'm interested in reproducing nudity concept unlearning part of your results.

I read the answer above but I think I need more details about image generation settings here. e.g., the size of your generated images, and random seed etc. Could you provide these details?

I would be better if you could provide the script that you used for generating _Df_ and _Dr_, or upload your experimental images (original "`data/nsfw`").

Thank you!
