### ISSUE TITLE
Can not decrease the foreget acc

### ISSUE THREAD

**Issue by moyudely** [OPTML-Group/Unlearn-Saliency#8]
Hi, thank you for sharing your great work! I have been trying to reproduce the algorithm recently. I followed the steps in README.md to train and forget. However, the forget acc did not decrease, or in other words, the decrease was not significant，even when using FT、 GA and RL. Did I overlook any details? If you could clarify, I would be extremely grateful！I conducted experiments on CIFAR10 and RESNET18.
For example, GA:
`python -u main_forget.py --save_dir Unlearn-Saliency-master/Classification/result_GA --mask Unlearn-Saliency-master/Classification/train_model/0model_SA_best.pth.tar --unlearn GA --num_indexes_to_replace 4500 --unlearn_lr 0.0001 --unlearn_epochs 5`
and the result is:
![image](https://github.com/OPTML-Group/Unlearn-Saliency/assets/92425280/6a33a313-ea94-4e10-917a-ec60314546e0)

**Comment by a-F1** [comment]
Thank you for your attention and interest in our work! I think this issue is caused by a too small learning rate. For example, for GA, you can appropriately increase the learning rate, such as to 5e-4 or 1e-3.
